default_install_hook_types: ["pre-commit", "commit-msg"]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
  - repo: https://github.com/crate-ci/typos
    rev: v1.45.1
    hooks:
      - id: typos
        stages: [pre-commit]
  - repo: https://github.com/crate-ci/committed
    rev: v1.1.10
    hooks:
      - id: committed
        stages: [commit-msg]
